mail:
  smtp: ${TRUSTIFI_URL:''}
  key: ${TRUSTIFI_KEY:''}
  secret: ${TRUSTIFI_SECRET:''}

server:
  port: ${PORT:8080}

spring:
  application:
    name: pincio-games
  http:
    multipart:
      enabled: true
  datasource:
    #initialization-mode: always
    password: ${DB_PW}
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    driverClassName: org.postgresql.Driver
    hikari:
      #connection-timeout: 30000
      idle-timeout: 120000
      max-lifetime: 120000
      maximum-pool-size: 3
    jpa:
      databasePlatform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
      show-sql: true
      generate-ddl: true
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka
#    fetch-registry: true
#  instance:
#    hostname: ${DOMAIN_NAME:localhost}
#    nonSecurePort: 80
#  password: ${EUREKA_USER_PASSWORD:password}


#logging:
#  level:
#    root: ERROR
#    org.hibernate: DEBUG