mail.service:
  host: ${TRUSTIFI_URL:''}
  key: ${TRUSTIFI_KEY:''}
  secret: ${TRUSTIFI_SECRET:''}

spring:
  application:
    name: pincio-games
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl
  http:
    multipart:
      enabled: true
  profiles: test
  datasource:
    platform: h2
    initialization-mode: always
    #url: jdbc:h2:~/test #;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE
    #driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
    #datasource:
    #  url: jdbc:h2:mem:dbpincio;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=TRUE;MODE=PostgreSQL;INIT=CREATE SCHEMA IF NOT EXISTS;SCHEMA=PINCIO
    #  username: sa
    #  password:
    #  driverClassName: org.h2.Driver
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    database: H2
    hibernate:
      ddl-auto: create-drop
      #dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    generate-ddl: true
#logging:
#  level:
#    root: ERROR
#    org.hibernate: DEBUG