mail.service:
  key: ${TRUSTIFI_KEY:''}
  secret: ${TRUSTIFI_SECRET:''}

server:
  port: ${PORT:8080}

spring:
  mail:
    host: ${TRUSTIFI_URL:''}
    port: 587
    username: <login user to smtp server>
    password: <login password to smtp server>
    properties.mail.smtp.auth: true
    properties.mail.smtp.starttls.enable: true
  application:
    name: pincio-games
  http:
    multipart:
      enabled: true
  profiles: prod
  datasource:
    initialization-mode: always
    password: ${DB_PW}
    platform: postgres
    url: ${DB_URL}
    username: ${DB_USER}
    driverClassName: org.postgresql.Driver
    hikari:
      #connection-timeout: 30000
      idle-timeout: 120000
      max-lifetime: 120000
      maximum-pool-size: 3
  jpa:
    databasePlatform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL-AUTO}
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka
#    fetch-registry: true
#  instance:
#    hostname: ${DOMAIN_NAME:localhost}
#    nonSecurePort: 80
#  password: ${EUREKA_USER_PASSWORD:password}


#logging:
#  level:
#    root: ERROR
#    org.hibernate: DEBUG