version: 2.1

#orbs:
#  maven: circleci/maven@1.1

#workflows:
#  maven_test:
#    jobs:
#      - maven/test

jobs: # a collection of steps
  test:
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: danieledagostino
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout:
      - run: ./mvnw test
  build: # runs not using Workflows must have a `build` job as entry point
    docker:
      - image: circleci/openjdk:stretch
        auth:
          username: danieledagostino
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
      steps:
        - checkout:
        - run: ./mvnw -Dmaven.test.skip=true package
workflows:
  version: 2
  build-then-test:
    jobs:
      - build:
      - test:
          requires:
            - build: